# Public (replicated) table. Written only on DB0, read-only on the replicas.
#
# Public tables use a UUID primary key generated by the database
# (gen_random_uuid()). A globally-unique id means DB0 can mint an id that never
# collides on any replica, so "upsert by id" converges across the whole topology
# without coordinating a shared sequence.
class CreateTenants < ActiveRecord::Migration[8.1]
  def change
    create_table :tenants, id: :uuid, default: -> { "gen_random_uuid()" } do |t|
      t.string :name, null: false
      t.string :subdomain, null: false

      t.timestamps
    end

    add_index :tenants, :subdomain, unique: true
  end
end
